name: Test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Create builder
        run: docker buildx create --use && docker buildx inspect --bootstrap

      - name: Test
        run: TEST_ALLOW_ALT_META=1 go test -v ./...